version: '3'

services:
  db:
    container_name: postgres-database
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    expose:
      - 27017
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.20
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456

volumes:
  postgres-db:
    external: true
